projects:
  dev:
    schemaPath: schema.graphql
    json: true
    extensions:
      endpoints:
        default:
          url: http://localhost:3000/
          headers:
            Authorization: "Bearer ${env:AUTH_TOKEN}"
