[package]
name = "twentyfive-stars-server"
version = "0.1.0"
authors = ["Blaine Bublitz <blaine.bublitz@gmail.com>"]
edition = "2018"

[[bin]]
name = "server"
path = "src/main.rs"

[dependencies]
async-graphql = "1.14.8"
async-graphql-tide = "1.14.7"
chrono = "0.4.11"
dotenv = "0.15.0"
env_logger = "0.7.1"
futures = "0.3.5"
smol = "0.1.0"
# Note: This is replaced by a fork that hard codes custom types and their OID
# That will be an issue after a new migration
sqlx = { git = "https://github.com/phated/sqlx", branch = "custom-types-040", features = ["postgres", "chrono", "uuid", "offline"] }
tide = "0.8.1"
uuid = { version = "0.8.1", features = ["serde", "v4"] }
